# Generated by Django 5.1.8 on 2025-04-13 17:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('input_type', models.CharField(choices=[('config_form', 'Config Form'), ('file_upload', 'File Upload')], default='config_form', max_length=50)),
                ('config_form', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectorInstance',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_config', models.JSONField()),
                ('schema_snapshot', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('None', 'None'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='None', max_length=20)),
                ('connector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='etl.connector')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connector_instances', to='billing.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DEPLOYING', 'Deploying'), ('ACTIVE', 'Active'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped'), ('DELETED', 'Deleted')], default='PENDING', max_length=20)),
                ('notes', models.TextField()),
                ('connector_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='etl.connectorinstance')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PipelineInstance',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='STARTED', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.pipeline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.connector')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
