# Generated by Django 5.1.8 on 2025-04-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorinstance',
            name='schema_status',
            field=models.CharField(choices=[('None', 'None'), ('DISCOVERING', 'Discovering'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='None', max_length=20),
        ),
    ]
