# Generated by Django 5.1.8 on 2025-04-03 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_plan_planfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeature',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='etl.plan'),
        ),
    ]
