# Generated by Django 5.1.8 on 2025-04-04 08:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_alter_planfeature_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('billing_cycle_day', models.CharField(max_length=255)),
                ('billing_frequency', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.plan')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
