# Generated by Django 5.1.8 on 2025-04-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
