# Generated by Django 5.1.8 on 2025-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='kms_key_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
